# frozen_string_literal: true

require 'bundler/setup'
require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

task :rust_build do
  `cargo rustc --release`
  # move dylib to right place and change name
  `mv -f ./target/release/libfib.dylib ./lib/fib/libfib.so` 
end

task :build => :rust_build
task :spec => :rust_build

task :rust_clean do
  `cargo clean`
  `rm -f ./lib/fib/libfib.so` # Change here according to your OS.
end

task :clean => :rust_clean



